sonar.projectKey=lebohang-bit_interra-trust-bank
sonar.organization=lebohang-bit
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/build/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
