version: 2.1

jobs:
  scan:
    docker:
      - image: node:20.18.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --legacy-peer-deps || true
      - run:
          name: Create dummy coverage
          command: |
            mkdir -p coverage
            echo "TN: LF:1 LH:1 END" > coverage/lcov.info
      - run:
          name: Install SonarScanner
          command: npm install -g sonar-scanner
      - run:
          name: SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=lebohang-bit_interra-trust-bank \
              -Dsonar.organization=lebohang-bit \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login= \
              -Dsonar.sources=src \
              -Dsonar.exclusions=**/node_modules/**,**/build/**

workflows:
  version: 2
  ci:
    jobs:
      - scan
